apiVersion: v1
kind: Namespace
metadata:
  name: k8s-watchdogs
  labels:
    kubernetes.io/metadata.name: k8s-watchdogs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-watchdogs-sa
  namespace: k8s-watchdogs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-watchdogs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-watchdogs-role
subjects:
- kind: ServiceAccount
  namespace: k8s-watchdogs
  name: k8s-watchdogs-sa
