name: 'Tag Release'

on:
  push:
    branches:
      - main
      - 'release-*'
    paths:
      - version.go

jobs:
  tag-release:
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - run: /usr/bin/git config --global user.email actions@github.com
      - run: /usr/bin/git config --global user.name 'GitHub Actions Release Tagger'
      - run: hack/tag-release.sh
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: make docker-buildx PLATFORMS=linux/arm64,linux/amd64 IMG=norseto/k8s-watchdogs:v$(hack/get-version.sh)
